name: my_dart_project
description: A simple Dart project that prints a message to the terminal.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  # Add any dependencies here
dev_dependencies:
  # Add any development dependencies here
flutter:
  uses-material-design: true